# Generated by Django 4.2.16 on 2024-11-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="travelPoint",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
