# Generated by Django 4.2.16 on 2024-11-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_alter_tour_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="breakfast",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tour",
            name="dinner",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tour",
            name="lunch",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
