# Generated by Django 4.2.16 on 2024-11-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_alter_tour_breakfast_alter_tour_dinner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="hotel",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
