# Generated by Django 4.2.16 on 2024-11-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_alter_tour_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="earlierGoDate",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tour",
            name="tourSpecial",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="tour",
            name="travelPoint",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
