# Generated by Django 4.2.16 on 2024-11-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_alter_tour_tourimage_alter_tour_tourlink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="tourSpecial",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
    ]
