# Generated by Django 4.2.16 on 2024-11-16 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_alter_tour_tourspecial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
